package module

import (
	"fmt"
	"strconv"
	"strings"

	"github.com/sprout-lang/sprout/internal/ast"
	"github.com/sprout-lang/sprout/internal/token"
)

// Render produces a single, self-contained Sprout source file for the
// bundle. The output needs no other files, so it can be copied or run
// anywhere. The build tool uses this to ship a program as one artifact.
//
// Each module becomes a function that returns a map of its exports. Import
// statements become calls to those functions. The module functions are
// emitted before the entry body, so every import is available when the
// program runs.
//
// The names __module_<n> and __m_<n> are reserved by the output. A source
// file that declares them would collide with the generated code.
func (b *Bundle) Render() string {
	var out strings.Builder
	fmt.Fprintf(&out, "// Generated by sprout build from %s.\n", b.Files[0].Path)
	out.WriteString("// This file is self-contained. Run it with: sprout run <file>\n")

	for _, mi := range b.Modules {
		f := b.Files[mi]
		fmt.Fprintf(&out, "\nfn __module_%d() {\n", mi)
		p := &printer{out: &out, bundle: b}
		p.body(f, 1)
		p.writeIndent()
		out.WriteString("return {")
		for i, name := range f.Exports {
			if i > 0 {
				out.WriteString(", ")
			}
			out.WriteString(strconv.Quote(name))
			out.WriteString(": ")
			out.WriteString(name)
		}
		out.WriteString("}\n")
		out.WriteString("}\n")
	}

	out.WriteString("\n")
	p := &printer{out: &out, bundle: b}
	p.body(b.Files[0], 0)
	return out.String()
}

// printer renders Sprout source text from an AST.
type printer struct {
	out    *strings.Builder
	bundle *Bundle
	indent int
}

// body writes the statements of f, hoisting its imports to the front.
func (p *printer) body(f *File, indent int) {
	p.indent = indent
	for _, s := range f.Prog.Stmts {
		if imp, ok := s.(*ast.ImportStmt); ok {
			p.importLine(imp)
		}
	}
	for _, s := range f.Prog.Stmts {
		if _, ok := s.(*ast.ImportStmt); ok {
			continue
		}
		p.stmt(s)
	}
}

// importLine writes the code that loads a module into the current scope.
func (p *printer) importLine(imp *ast.ImportStmt) {
	if imp.Module < 0 || imp.Module >= len(p.bundle.Files) {
		return
	}
	target := p.bundle.Files[imp.Module]
	p.writeIndent()
	fmt.Fprintf(p.out, "let __m_%d = __module_%d()\n", imp.Module, imp.Module)
	if imp.Alias != nil {
		p.writeIndent()
		fmt.Fprintf(p.out, "const %s = __m_%d\n", imp.Alias.Name, imp.Module)
		return
	}
	for _, name := range target.Exports {
		p.writeIndent()
		fmt.Fprintf(p.out, "const %s = __m_%d[%s]\n", name, imp.Module, strconv.Quote(name))
	}
}

// stmt writes one statement at the current indent.
func (p *printer) stmt(s ast.Stmt) {
	switch n := s.(type) {
	case *ast.LetStmt:
		kw := "let"
		if n.IsConst {
			kw = "const"
		}
		p.writeIndent()
		p.out.WriteString(kw)
		p.out.WriteString(" ")
		p.out.WriteString(n.Name.Name)
		if n.Type != nil {
			p.out.WriteString(": ")
			p.out.WriteString(n.Type.Name)
		}
		p.out.WriteString(" = ")
		p.out.WriteString(p.expr(n.Value, 0))
		p.out.WriteString("\n")

	case *ast.FnStmt:
		p.writeIndent()
		p.out.WriteString("fn ")
		p.out.WriteString(n.Name.Name)
		p.out.WriteString(p.params(n.Params))
		p.out.WriteString(" ")
		p.block(n.Body)
		p.out.WriteString("\n")

	case *ast.IfStmt:
		p.writeIndent()
		p.out.WriteString("if ")
		p.out.WriteString(p.expr(n.Cond, 0))
		p.out.WriteString(" ")
		p.block(n.Then)
		for _, b := range n.Elifs {
			p.writeIndent()
			p.out.WriteString("elif ")
			p.out.WriteString(p.expr(b.Cond, 0))
			p.out.WriteString(" ")
			p.block(b.Body)
		}
		if n.Else != nil {
			p.writeIndent()
			p.out.WriteString("else ")
			p.block(n.Else)
		}
		p.out.WriteString("\n")

	case *ast.WhileStmt:
		p.writeIndent()
		p.out.WriteString("while ")
		p.out.WriteString(p.expr(n.Cond, 0))
		p.out.WriteString(" ")
		p.block(n.Body)
		p.out.WriteString("\n")

	case *ast.ForInStmt:
		p.writeIndent()
		p.out.WriteString("for ")
		p.out.WriteString(n.Var.Name)
		p.out.WriteString(" in ")
		p.out.WriteString(p.expr(n.Iterable, 0))
		p.out.WriteString(" ")
		p.block(n.Body)
		p.out.WriteString("\n")

	case *ast.ReturnStmt:
		p.writeIndent()
		p.out.WriteString("return")
		if n.Value != nil {
			p.out.WriteString(" ")
			p.out.WriteString(p.expr(n.Value, 0))
		}
		p.out.WriteString("\n")

	case *ast.BreakStmt:
		p.writeIndent()
		p.out.WriteString("break\n")

	case *ast.ContinueStmt:
		p.writeIndent()
		p.out.WriteString("continue\n")

	case *ast.ExprStmt:
		p.writeIndent()
		p.out.WriteString(p.expr(n.X, 0))
		p.out.WriteString("\n")
	}
}

// block writes a braced statement list one level deeper.
func (p *printer) block(b *ast.Block) {
	p.out.WriteString("{\n")
	p.indent++
	for _, s := range b.Stmts {
		p.stmt(s)
	}
	p.indent--
	p.writeIndent()
	p.out.WriteString("}")
}

// params renders a parameter list with optional type annotations.
func (p *printer) params(params []*ast.Param) string {
	parts := make([]string, len(params))
	for i, pr := range params {
		if pr.Type != nil {
			parts[i] = pr.Name.Name + ": " + pr.Type.Name
		} else {
			parts[i] = pr.Name.Name
		}
	}
	return "(" + strings.Join(parts, ", ") + ")"
}

// expr renders an expression, adding parentheses when its own precedence is
// looser than min.
func (p *printer) expr(e ast.Expr, min int) string {
	prec := ownPrec(e)
	s := p.exprInner(e)
	if prec < min {
		return "(" + s + ")"
	}
	return s
}

func (p *printer) exprInner(e ast.Expr) string {
	switch n := e.(type) {
	case *ast.Ident:
		return n.Name
	case *ast.IntLit:
		return strconv.FormatInt(n.Value, 10)
	case *ast.FloatLit:
		return formatFloat(n.Value)
	case *ast.StrLit:
		return strconv.Quote(n.Value)
	case *ast.BoolLit:
		if n.Value {
			return "true"
		}
		return "false"
	case *ast.NilLit:
		return "nil"
	case *ast.ListLit:
		parts := make([]string, len(n.Elems))
		for i, el := range n.Elems {
			parts[i] = p.expr(el, 0)
		}
		return "[" + strings.Join(parts, ", ") + "]"
	case *ast.MapLit:
		parts := make([]string, len(n.Entries))
		for i, en := range n.Entries {
			parts[i] = p.expr(en.Key, 0) + ": " + p.expr(en.Value, 0)
		}
		return "{" + strings.Join(parts, ", ") + "}"
	case *ast.UnaryExpr:
		op := n.Op.String()
		if n.Op == token.NOT {
			op = "not"
		}
		return op + " " + p.expr(n.X, 9)
	case *ast.BinaryExpr:
		if n.Op == token.CARET {
			return p.expr(n.Left, 10) + " ^ " + p.expr(n.Right, 9)
		}
		prec := binaryPrec(n.Op)
		return p.expr(n.Left, prec) + " " + n.Op.String() + " " + p.expr(n.Right, prec+1)
	case *ast.AssignExpr:
		return p.expr(n.Target, 2) + " = " + p.expr(n.Value, 1)
	case *ast.CallExpr:
		parts := make([]string, len(n.Args))
		for i, a := range n.Args {
			parts[i] = p.expr(a, 0)
		}
		return p.expr(n.Callee, 10) + "(" + strings.Join(parts, ", ") + ")"
	case *ast.IndexExpr:
		return p.expr(n.X, 10) + "[" + p.expr(n.Index, 0) + "]"
	case *ast.FnExpr:
		return "fn" + p.params(n.Params) + " " + p.blockInline(n.Body)
	}
	return "nil"
}

// blockInline renders a block on a single line for use inside an expression.
func (p *printer) blockInline(b *ast.Block) string {
	save := p.indent
	parts := make([]string, len(b.Stmts))
	for i, s := range b.Stmts {
		switch n := s.(type) {
		case *ast.ReturnStmt:
			if n.Value != nil {
				parts[i] = "return " + p.expr(n.Value, 0)
			} else {
				parts[i] = "return"
			}
		case *ast.ExprStmt:
			parts[i] = p.expr(n.X, 0)
		case *ast.BreakStmt:
			parts[i] = "break"
		case *ast.ContinueStmt:
			parts[i] = "continue"
		default:
			parts[i] = p.oneLineStmt(s)
		}
	}
	p.indent = save
	return "{" + strings.Join(parts, " ") + "}"
}

// oneLineStmt renders a statement on one line.
func (p *printer) oneLineStmt(s ast.Stmt) string {
	var b strings.Builder
	prev := p.out
	p.out = &b
	save := p.indent
	p.stmt(s)
	p.out = prev
	p.indent = save
	return strings.TrimSuffix(b.String(), "\n")
}

// indent writes the current indentation.
func (p *printer) writeIndent() { p.indentAt(p.indent) }

// indentAt writes n levels of indentation.
func (p *printer) indentAt(n int) {
	for i := 0; i < n; i++ {
		p.out.WriteString("\t")
	}
}

// ownPrec returns the precedence at which e binds.
func ownPrec(e ast.Expr) int {
	switch n := e.(type) {
	case *ast.BinaryExpr:
		return binaryPrec(n.Op)
	case *ast.UnaryExpr:
		return 8
	case *ast.AssignExpr:
		return 1
	}
	return 10
}

// binaryPrec maps a binary operator to its binding power.
func binaryPrec(k token.Kind) int {
	switch k {
	case token.OR:
		return 2
	case token.AND:
		return 3
	case token.EQ, token.NEQ:
		return 4
	case token.LT, token.LE, token.GT, token.GE:
		return 5
	case token.PLUS, token.MINUS:
		return 6
	case token.STAR, token.SLASH, token.PERCENT:
		return 7
	case token.CARET:
		return 9
	}
	return 0
}

func formatFloat(f float64) string {
	return strconv.FormatFloat(f, 'g', -1, 64)
}
