package module

import (
	"strings"
	"testing"

	"github.com/sprout-lang/sprout/internal/diag"
	"github.com/sprout-lang/sprout/internal/parser"
	"github.com/sprout-lang/sprout/internal/source"
)

func TestRenderBundle(t *testing.T) {
	dir := t.TempDir()
	writeModule(t, dir, "lib/g.spr",
		"export fn greet(name) { return \"hello, \" + name }\nexport const punc = \"!\"\n")
	writeModule(t, dir, "main.spr",
		"import \"lib/g.spr\"\nprint(greet(\"world\") + punc)\n")
	bundle := expectLoadClean(t, dir)

	out := bundle.Render()
	for _, want := range []string{
		"Generated by sprout build",
		"fn __module_1() {",
		`const greet = __m_1["greet"]`,
		`const punc = __m_1["punc"]`,
		`return {"greet": greet, "punc": punc}`,
		`let __m_1 = __module_1()`,
		`print(greet("world") + punc)`,
	} {
		if !strings.Contains(out, want) {
			t.Errorf("bundle missing %q:\n%s", want, out)
		}
	}
}

func TestRenderBundleAliasImport(t *testing.T) {
	dir := t.TempDir()
	writeModule(t, dir, "calc.spr",
		"export fn add(a, b) { return a + b }\n")
	writeModule(t, dir, "main.spr",
		"import calc from \"calc.spr\"\nprint(calc[\"add\"](1, 2))\n")
	bundle := expectLoadClean(t, dir)

	out := bundle.Render()
	for _, want := range []string{
		"fn __module_1() {",
		"let __m_1 = __module_1()",
		"const calc = __m_1",
		`print(calc["add"](1, 2))`,
	} {
		if !strings.Contains(out, want) {
			t.Errorf("bundle missing %q:\n%s", want, out)
		}
	}
}

func TestRenderBundleParses(t *testing.T) {
	dir := t.TempDir()
	writeModule(t, dir, "lib/a.spr",
		"export fn a(x) { return x * 2 }\n")
	writeModule(t, dir, "lib/b.spr",
		"import \"a.spr\"\nexport fn b(x) { return a(x) + 1 }\n")
	writeModule(t, dir, "main.spr",
		"import lib from \"lib/b.spr\"\nprint(lib[\"b\"](2))\n")

	bundle := expectLoadClean(t, dir)
	out := bundle.Render()
	file := source.NewFile("bundle.spr", out)
	_, diags := parser.Parse(file)
	for _, d := range diags {
		if d.Severity == diag.SeverityError {
			t.Errorf("rendered bundle does not parse: %s", d.Message)
		}
	}
}

func TestRenderTransitiveOrder(t *testing.T) {
	dir := t.TempDir()
	writeModule(t, dir, "lib/a.spr", "export fn a() { return 1 }\n")
	writeModule(t, dir, "lib/b.spr", "import \"a.spr\"\nexport fn b() { return a() + 1 }\n")
	writeModule(t, dir, "main.spr", "import \"lib/b.spr\"\nprint(b())\n")
	bundle := expectLoadClean(t, dir)

	out := bundle.Render()
	// The main body runs after every module function is defined, so its
	// statements must follow the module definitions.
	mainBody := strings.Index(out, "print(b())")
	if mainBody < 0 {
		t.Fatalf("bundle has no main body:\n%s", out)
	}
	if strings.Count(out[:mainBody], "fn __module_") != 2 {
		t.Errorf("expected two module definitions before the main body:\n%s", out)
	}
	// The hoisted import rewrite appears before the statement that uses it.
	if strings.Index(out, "let __m_") > strings.Index(out, "const b =") {
		t.Errorf("import must load before its name is bound:\n%s", out)
	}
}

func TestRenderModuleWithNoExports(t *testing.T) {
	dir := t.TempDir()
	writeModule(t, dir, "side.spr", "print(\"side effect\")\n")
	writeModule(t, dir, "main.spr", "import \"side.spr\"\nprint(\"main\")\n")
	bundle := expectLoadClean(t, dir)

	out := bundle.Render()
	if !strings.Contains(out, "return {}") {
		t.Errorf("no-export module should return an empty map:\n%s", out)
	}
}
